name: A Walk in the Park
description:
meta_description: "Things to do in Disney that are not rides"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /disney-blog/
domain_name: 'http://jkutner.github.io'
google_analytics: 'UA-60067944-1'

# Details for the RSS feed generator
url:            'http://jkutner.github.io'
author:         'Vader Cat'
